defaults:
  - agent: diayn

# mode
reward_free: false

# task settings
task: texturedwalker_stand
obs_type: pixels
frame_stack: 3 
action_repeat: 2 # Set to 2 to match URLB pixel-based learning
discount: 0.99

# Dummy variables to satisfy Hydra agent interpolations
batch_size: 256
nstep: 3
update_encoder: false
use_tb: false

# pretrained
snapshot_ts: 2000000
snapshot_base_dir: /mnt/faster0/bm844/models
snapshot_path: null

# search settings
num_candidates: 16
eval_steps: 50 

# misc
seed: 1
device: cuda
use_wandb: true
experiment: zero_shot